# Generated by Django 3.2.8 on 2021-11-08 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mall',
            name='date',
            field=models.DateField(verbose_name='date-item-entered'),
        ),
    ]
