# Generated by Django 3.2.9 on 2021-11-29 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_mall_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mall',
            options={'ordering': ['item_price']},
        ),
    ]
