# Generated by Django 3.2.8 on 2021-12-01 20:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_mall_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mall',
            options={'ordering': ['item_price']},
        ),
        migrations.RemoveField(
            model_name='grocery',
            name='item_rate',
        ),
        migrations.RemoveField(
            model_name='mall',
            name='date',
        ),
        migrations.AddField(
            model_name='mall',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mall',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
