# Generated by Django 3.2.9 on 2021-12-01 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20211201_1327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grocery',
            name='item_comment',
        ),
    ]
