# Generated by Django 3.2.9 on 2021-12-07 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_mall_options'),
        ('app', '0004_remove_grocery_item_comment'),
    ]

    operations = [
    ]
