# Generated by Django 3.2.9 on 2021-12-08 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_merge_20211202_1312'),
        ('app', '0005_merge_20211207_1226'),
    ]

    operations = [
    ]
