# Generated by Django 3.2.9 on 2021-12-08 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_merge_20211207_1630'),
        ('app', '0006_merge_20211208_1129'),
    ]

    operations = [
    ]
